### PR TITLE
PR: Issue 66: Pull Request Template Changes

### PR DESCRIPTION
**Pull request by bsoyka**
# Description
Completely fixes: #66

This PR follows the new template. Enjoy!

### CODE REVIEW

**Comment by lucasvazq** [comment]
thanks dude!

**Comment by lucasvazq** [comment]
Look good, probably I will copy some of that for the issues templates

**Comment by lucasvazq** [comment]
#75

**Comment by bsoyka** [comment]
> thanks dude!

No worries! Glad I could help!

**Pull request merged**
